# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ui import SpyderDialog


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self) -> None:
        super().__init__(None, QtCore.Qt.WindowType.Window)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.setFixedSize(self.width(), self.height())
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Spyder = QtWidgets.QPushButton(self.centralwidget)
        self.Spyder.setGeometry(QtCore.QRect(200, 330, 200, 100))
        self.Spyder.setObjectName("Spyder")
        self.Video = QtWidgets.QPushButton(self.centralwidget)
        self.Video.setGeometry(QtCore.QRect(420, 330, 200, 100))
        self.Video.setObjectName("Video")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(200, 170, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.init()

    def init(self):
        self.Spyder.clicked.connect(self.spyder_)
        self.Video.clicked.connect(self.video_)

    def spyder_(self):
        spyder = SpyderDialog.Ui_Spyder(self)
        spyder.show()

    def video_(self):
        pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "智障小工具"))
        self.Spyder.setText(_translate("MainWindow", "爬取图片"))
        self.Video.setText(_translate("MainWindow", "视频抽帧"))
        self.Title.setText(_translate("MainWindow", "智障小工具"))
